spring:
  application:
    name: etapa1DAC

  datasource:
    url: jdbc:postgresql://localhost:5432/dac
    username: dac
    password: dac
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    host: localhost
    port: 5672
    username: dac
    password: dac

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: 'aksdaksda'
    password: 'dsfsdfsdf'
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 50000
          timeout: 50000
          writetimeout: 50000

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

rabbitmq:
  email:
    queue: email-request-queue
    exchange: email-exchange
    response-success: email-response-success-queue
    response-error: email-response-error-queue
    routing-key:
      queue: email-request
      response-success: email-response-success
      response-error: email-response-error