-- Criação da tabela account
create table account (
    active boolean not null,
    id bigint generated by default as identity,
    password varchar(128) not null,
    email varchar(255) not null,
    name varchar(255) not null,
    primary key (id)
);

-- Criação da tabela event
create table event (
    created_at timestamp(6),
    id bigint generated by default as identity,
    description varchar(500) not null,
    category varchar(255),
    name varchar(255) not null,
    primary key (id)
);

-- Criação da tabela event_date
create table event_date (
    created_at timestamp(6),
    end_time timestamp(6) not null,
    event_id bigint not null,
    id bigint generated by default as identity,
    start_time timestamp(6) not null,
    location varchar(255) not null,
    primary key (id),
    constraint unique_location_start_time unique (location, start_time)
);

-- Criação da tabela permission
create table permission (
    id bigint generated by default as identity,
    user_id bigint,
    name varchar(255),
    primary key (id)
);

-- Criação da tabela ticket
create table ticket (
    quantity integer not null,
    valid_days_left integer not null,
    created_at timestamp(6),
    event_id bigint not null,
    id bigint generated by default as identity,
    owner_id bigint not null,
    ticket_type_id bigint not null,
    primary key (id)
);

-- Criação da tabela ticket_required_fields
create table ticket_required_fields (
    ticket_id bigint not null,
    field_name varchar(255) not null,
    field_value varchar(255),
    primary key (ticket_id, field_name)
);

-- Criação da tabela ticket_type
create table ticket_type (
    price float(53) not null,
    sold_quantity integer not null,
    total_quantity integer not null,
    id bigint generated by default as identity,
    name varchar(255) not null,
    primary key (id)
);

-- Criação da tabela ticket_type_required_fields
create table ticket_type_required_fields (
    ticket_type_id bigint not null,
    field_name varchar(255) not null,
    field_value TEXT,
    primary key (ticket_type_id, field_name)
);

-- Criação das constraints de chave estrangeira

-- Adicionando constraint de chave estrangeira em event_date
alter table event_date
    add constraint FK_event_date_event
    foreign key (event_id)
    references event;

-- Adicionando constraint de chave estrangeira em permission
alter table permission
    add constraint FK_permission_account
    foreign key (user_id)
    references account;

-- Adicionando constraint de chave estrangeira em ticket
alter table ticket
    add constraint FK_ticket_event
    foreign key (event_id)
    references event;

alter table ticket
    add constraint FK_ticket_owner
    foreign key (owner_id)
    references account;

alter table ticket
    add constraint FK_ticket_ticket_type
    foreign key (ticket_type_id)
    references ticket_type;

-- Adicionando constraint de chave estrangeira em ticket_required_fields
alter table ticket_required_fields
    add constraint FK_ticket_required_fields_ticket
    foreign key (ticket_id)
    references ticket;

-- Adicionando constraint de chave estrangeira em ticket_type_required_fields
alter table ticket_type_required_fields
    add constraint FK_ticket_type_required_fields_ticket_type
    foreign key (ticket_type_id)
    references ticket_type;
